name: "Install Calibre"

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1

      - name: Install calibre dependencies
        run: sudo apt-get update -y && sudo apt-get install --no-install-recommends -y libegl1 libopengl0

      - name: Get latest calibre version
        id: calibrelatest
        run: |
          tag="$(curl -L --retry 2 --silent 'https://api.github.com/repos/kovidgoyal/calibre/releases/latest' | jq -r .tag_name)" && \
          echo "::set-output name=ver::${tag#*v}"

      - name: Binaries Cache
        id: cache-bin
        uses: actions/cache@v3
        with:
          path: cache/calibre
          key: cache-calibre-x86_64-${{ steps.calibrelatest.outputs.ver }}

      - name: Install calibre
        run: sh .github/workflows/install_calibre.sh
